apiVersion: batch/v1
kind: Job
metadata:
  name: apply-migrations
spec:
  template:
    spec:
      containers:
      - name: go-apply-migrations
        image: playbackdev/go-apply-migtaions:latest
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: db_pass
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: db_name
      restartPolicy: Never
  backoffLimit: 4