package migrations

import (
	"fmt"
	"go-apply-migrations/internal/core/database"
)

type Migration struct {
	name  string
	query string
}

var migrations = [2]Migration{
	Migration{
		name: "1_schema",
		query: `
			CREATE SCHEMA otus_3;
		`,
	},
	Migration{
		name: "2_users",
		query: `
			CREATE TABLE otus_3.users (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				username VARCHAR(255) UNIQUE,
				first_name VARCHAR(255),
				last_name VARCHAR(255),
				email VARCHAR(64),
				phone VARCHAR(36),
				updated_at TIMESTAMP,
				created_at TIMESTAMP
			);
		`,
	},
}

func Migrate() error {
	db := database.GetDb()

	for _, m := range migrations {
		fmt.Println(fmt.Sprintf("Migrating %s...", m.name))
		_, err := db.Exec(m.query)

		if err != nil {
			return err
		}
		fmt.Println(fmt.Sprintf("%s migrated successfully", m.name))
	}
	return nil
}
