version: "3.7"
services:
  postgres:
    container_name: Postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
  migrations-app:
    container_name: MigrationsApp
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      DB_HOST: "postgres"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
    restart: on-failure:5
    depends_on:
      - postgres
    networks:
      - default

volumes:
  data: